# Hacktiv8 Introduction to Data Science - Sesi 4

Sesi 4:

- Numpy

## Creating Array
### another markdown
#### markdown

In [1]:
#import pkg numpy 
import numpy as np

In [3]:
# install numpy karna saya pakai anaconda
!conda install numpy
# or using pip
!pip install numpy

Solving environment: ...working... done

# All requested packages already installed.



In [4]:
#create array with numpy 
a = np.array([1, 2, 3, 4])

In [5]:
#call var a
a

array([1, 2, 3, 4])

In [6]:
#create 0 dalam array jumlah 5 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
#create 1 dalam 5 array
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
#create empty bilangan 1 
np.empty(5)

array([1., 1., 1., 1., 1.])

In [9]:
#bilangan ber urut 
np.arange(11)       #auto mulai dari 0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#create ragnge start 0 - 10
np.arange(5, 11)    #(start, stop)

array([ 5,  6,  7,  8,  9, 10])

In [11]:
#create range  
np.arange(0, 50, 5)     #(start, stop, step)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [12]:
#call out array
print(np.arange(0,10,2))

[0 2 4 6 8]


In [13]:
#create bilangan ganjil sampai 100
b = np.arange(1,100,2)
b


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [14]:
print(b[2])

5


In [15]:
# create a list of python

a =["0",1,"two",4]      
print(a[2])

two


## Add, Remove, and Sort

In [19]:
#create array numpy 'arr'
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr)

[1 2 3 4 5 6 7 8]


In [21]:
#add more number di arrNew
arrNew = np.append(arr, [1, 2])
print(arrNew)

[1 2 3 4 5 6 7 8 1 2]


In [22]:
#create list 
c=[[[1,2,3],[4,5,6],[7,8,9]]]
c

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [23]:
#convert list to array numpy
c= np.array(c)
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [24]:
#call our new array > akan arr + 1,2
arrNew

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [25]:
#delete array ke 1 (yaitu : 2)
arrNew = np.delete(arrNew, 1)

In [26]:
arrNew

array([1, 3, 4, 5, 6, 7, 8, 1, 2])

In [27]:
#sort array 
np.sort(arrNew)

array([1, 1, 2, 3, 4, 5, 6, 7, 8])

## Shape and Size

In [28]:
#create 3d array, dimana 2 baris dan 3 kolom
array_example = np.array([[[0, 1, 2, 3],[4, 5, 6, 7]],
                          [[0, 1, 2, 3],[4, 5, 6, 7]],
                          [[0, 1, 2, 3],[4, 5, 6, 7]]])

In [29]:
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [30]:
#jumlah axex, dimensi dari array
array_example.ndim

3

In [31]:
#jumlah total array
array_example.size

24

In [32]:
#menunkjukan jumlah elemen di arra nya
array_example.shape

(3, 2, 4)

In [33]:
# create 2D array 3x3
darray=np.array([[1,2,3],[4,5,6],[7,8,9]])
darray


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
# create 2D array 3x4
farray=np.array([[11,12,13,14],[24,25,26,27],[37,38,39,30]])
farray

array([[11, 12, 13, 14],
       [24, 25, 26, 27],
       [37, 38, 39, 30]])

In [35]:
# can it work 2D array 3x4??
garray=np.array([[11,12,13,14],[24,25,26],[37,38,39,30]])
garray

<ipython-input-35-48e360a2794b>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  garray=np.array([[11,12,13,14],[24,25,26],[37,38,39,30]])


array([list([11, 12, 13, 14]), list([24, 25, 26]), list([37, 38, 39, 30])],
      dtype=object)

In [36]:
#darray.ndim
farray.ndim

2

In [37]:
#darray.shape
farray.shape

(3, 4)

In [38]:
#access element on the first row second columns
farray[1][1]

25

In [39]:
#accecc eleemnt on the irst row and till 3rd coloms
farray[0][0:3]

array([11, 12, 13])

In [40]:
#access element 27 and 30
farray[1:3, 3]

print(farray[1][3])
print(farray[2][3])

27
30


In [41]:
#access element 27 and 30
farray[1:3, 3]

array([27, 30])

## Reshape

In [42]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [43]:
a.shape

(6,)

In [44]:
b = a.reshape(3, 2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [45]:
b.shape

(3, 2)

## Convert 1D to 2D

In [58]:
#array 1d a
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
a.ndim

[1 2 3 4 5 6]


1

In [55]:
a.shape

(6,)

In [59]:
#add more dim using newaxis
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [60]:
a.ndim

1

In [61]:
#convert 1d arra to row vector by insert axis
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [51]:
#convert 1d arra to column vector by insert axis
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [92]:
a.shape

(6,)

In [93]:
#to ad an axis at incex position 1 
b = np.expand_dims(a, axis=1)

In [94]:
b.shape

(6, 1)

In [95]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [34]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [35]:
c

array([[1, 2, 3, 4, 5, 6]])

## Indexing and Slicing

In [96]:
data = np.array([1, 2, 3])

In [97]:
print(data)

[1 2 3]


In [98]:
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

1
2
[1 2]
[2 3]
[2 3]


In [99]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [100]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [102]:
#call out values in array yang kurang dari 10
a[a<=10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
#call out angka yg sama dengan atau lebih dari 5
five_up = (a>=5)

a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [104]:
#call out element are divisible by 2
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [47]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## Creating Array From Existing Data

slicing indexing 
- np.vstack()
- np.stack()
- np.hplit()
- .view
- .copy

In [105]:
#this is our array 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [106]:
arr     #call out array 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
#call out array dari array ke 3-8
arrNew = arr[3:8]
print(arrNew)

[4 5 6 7 8]


In [123]:
#dua array
a_1 = np.array([[1, 1,0],
               [2, 2,0]])
print(a_1)

[[1 1 0]
 [2 2 0]]


In [124]:
#dua array
a_2 = np.array([[3, 3],
               [4, 4]])
print(a_2)

[[3 3]
 [4 4]]


In [122]:
#stack 2 array, numpuk 2 array dengan ukuran yang sama 
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [125]:
#numpuk 2 array secara vertikal
np.hstack((a_1, a_2))

array([[1, 1, 0, 3, 3],
       [2, 2, 0, 4, 4]])

In [126]:
#membagi sebuah array become smaller
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [127]:
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [128]:
#split array equally shaped arays jadi 3
np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [130]:
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [131]:
#create new array object that looks at the same data
b = arrsplit.view()

print(b)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [132]:
#make a complate copy dari array 
c = arrsplit.copy()

print(c)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


## Basic Array Operations

In [133]:
#create 2 array data and ones > data have value trus ones
data = np.array([1, 2, 3, 4])
ones = np.ones(4)

In [134]:
print(data)
print(ones)

[1 2 3 4]
[1. 1. 1. 1.]


In [135]:
print(data+ones)
print(data-ones)
print(data*ones)
print(data/ones)

[2. 3. 4. 5.]
[0. 1. 2. 3.]
[1. 2. 3. 4.]
[1. 2. 3. 4.]


In [136]:
print(data.sum())
print(ones.sum())

10
4.0


In [138]:
#2d array 
b = np.array([[1, 1], [2, 2]])
print(b)

[[1 1]
 [2 2]]


In [139]:
b.sum()

6

In [140]:
#sum row
b.sum(axis=0)

array([3, 3])

In [141]:
#sum column
b.sum(axis=1)

array([2, 4])

In [144]:
# array dikali nilai 2
b *2

array([[2, 2],
       [4, 4]])

In [145]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [76]:
A.sum()

4.8595784

In [77]:
A.sum(axis=0)

array([1.12378257, 1.04875507, 1.01034462, 1.67669614])

In [78]:
A.sum(axis=1)

array([1.51832856, 1.55434556, 1.78690428])

In [79]:
#nilai min dari array
A.min()

0.05093587

In [148]:

A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [147]:
A.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

In [149]:
A.max()

0.82485143

In [83]:
A.max(axis=0)

array([0.54627315, 0.82485143, 0.40067661, 0.56917101])

In [84]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

## Matrices

In [150]:
#
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [151]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [152]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [153]:
np.random.random((3, 2))

array([[0.16762255, 0.65650912],
       [0.12061449, 0.83469927],
       [0.81151629, 0.31125304]])

In [154]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Matrix Arithmetic

In [90]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [91]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [94]:
print(data + ones)
print(data - ones)
print(data * ones)
print(data / ones)

[[2. 3.]
 [4. 5.]]
[[0. 1.]
 [2. 3.]]
[[1. 2.]
 [3. 4.]]
[[1. 2.]
 [3. 4.]]


In [95]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [96]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


## Dot Product

In [155]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [156]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [158]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [159]:
print(data[0, 1])
print(data[1:3])
print(data[0:2, 0])

2
[[3 4]
 [5 6]]
[1 3]


## Matrix Aggregation

In [105]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [106]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [107]:
print(data.max(axis=1))
print(data.min(axis=1))
print(data.sum(axis=1))

[2 4 6]
[1 3 5]
[ 3  7 11]


## Transposing and Reshaping

In [108]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [109]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [111]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [112]:
data_col.shape

(6, 1)

In [115]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [119]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


## N-Dimensional Array

In [120]:
ndarr = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [125]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [128]:
np.zeros((4, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [131]:
np.random.random((4, 3, 2))

array([[[0.4882246 , 0.10389851],
        [0.58848051, 0.67859204],
        [0.7785528 , 0.42225151]],

       [[0.363801  , 0.24722927],
        [0.79298283, 0.80326886],
        [0.92951015, 0.14534498]],

       [[0.36354433, 0.5067065 ],
        [0.04525132, 0.05782362],
        [0.28128721, 0.69389967]],

       [[0.13827522, 0.14155922],
        [0.22517379, 0.30487521],
        [0.9481453 , 0.04072419]]])

## Flaten N-Dimensional Array

In [132]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [133]:
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [134]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Notes on Numpy Vector

In [135]:
a = np.random.rand(5)
print(a)

[0.23922181 0.80742798 0.24476393 0.23992297 0.82203954]


In [136]:
a.shape # Rank 1 Array

(5,)

In [137]:
a.T

array([0.23922181, 0.80742798, 0.24476393, 0.23992297, 0.82203954])

In [138]:
np.dot(a, a.T)

1.502388420652875

In [139]:
a = np.random.rand(5, 1) # column vector
print(a)

[[0.20979547]
 [0.01286554]
 [0.56477516]
 [0.18631046]
 [0.67895426]]


In [140]:
a.shape

(5, 1)

In [141]:
a.T

array([[0.20979547, 0.01286554, 0.56477516, 0.18631046, 0.67895426]])

In [142]:
np.dot(a, a.T)

array([[4.40141378e-02, 2.69913267e-03, 1.18487268e-01, 3.90870907e-02,
        1.42441526e-01],
       [2.69913267e-03, 1.65522206e-04, 7.26613931e-03, 2.39698535e-03,
        8.73511549e-03],
       [1.18487268e-01, 7.26613931e-03, 3.18970981e-01, 1.05223522e-01,
        3.83456501e-01],
       [3.90870907e-02, 2.39698535e-03, 1.05223522e-01, 3.47115889e-02,
        1.26496283e-01],
       [1.42441526e-01, 8.73511549e-03, 3.83456501e-01, 1.26496283e-01,
        4.60978889e-01]])

In [143]:
a = np.random.rand(1, 5) # row vector
print(a)

[[0.93258393 0.96877229 0.21536587 0.55283545 0.92999658]]
